### ISSUE TITLE
FlatCompat utility needs documentation (or has wrong documentation)

### ISSUE THREAD

**Issue by matthew-dean** [eslint/eslintrc#147] opened 2024-01-25 19:32 UTC
Even though the documentation says that `recommendedConfig` is optional, I'm getting this error for ESLint:
```
TypeError: Missing parameter 'recommendedConfig' in FlatCompat constructor
```
I think this is because a Nuxt config uses a non-flat file and is using 'eslint:recommended'. But the documentation doesn't make clear when you would / would not need that option.

**Comment by aladdin-add** [comment] 2024-01-26 01:48
Duplicate of #127 

and I agreed the docs can be improved.

**Comment by nzakas** [comment] 2024-01-26 20:13
Yeah, you only get that error if a config is using `eslint:recommended`. I'll update the README.

**Closed** 2024-01-27 04:28 UTC
Labels: documentation, enhancement
