### ISSUE TITLE
Bug: `FlatCompat.config` doesn't work with `overrides`

### ISSUE THREAD

**Issue by Ayc0** [eslint/eslintrc#125] opened 2023-08-02 22:02 UTC
## Step to reproduce

- `eslint`: `8.46.0`
- `@eslint/eslintrc`: `2.1.1`

You can open & run: https://runkit.com/ayc0/64cac9cf2e21ef0008bee16d

<details><summary>This runkit gets lost / deleted / edited, here is the raw code</summary>

```js
const code = 'console.log(process.pwd())';

const run = async (ESLint, config, filePath) => {
    const eslint = new ESLint(config);
    
    // 2. Lint text.
    const results = await eslint.lintText(code, { filePath });

    // 3. Format the results.
    const formatter = await eslint.loadFormatter("stylish");
    const resultText = formatter.format(results);

    // 4. Output it.
    console.log(resultText);
}

const baseConfig = {
    rules: {
      'no-undef': 'error',
    },
    overrides: [{
        files: ['node.js'],
        env: {
            node: true
        },
    }]
}

const { ESLint } = require("eslint@8.46.0");

const config = { useEslintrc: false, overrideConfig: baseConfig };

await run(ESLint, config, 'classic/node.js'); // should be okay ✅
await run(ESLint, config, 'classic/not-node.js'); // should have an error ✅
// Check output

const { FlatCompat } = require("@eslint/eslintrc@2.1.1");
const { FlatESLint } = require("eslint@8.46.0/use-at-your-own-risk");


const compat = new FlatCompat({
    baseDirectory: __dirname
});
const flatConfig = compat.config(baseConfig);

console.log(flatConfig);

await run(FlatESLint, { overrideConfigFile: true, overrideConfig: flatConfig }, 'flat/node.js'); // should be okay ✅
await run(FlatESLint, { overrideConfigFile: true, overrideConfig: flatConfig }, 'flat/not-node.js'); // should have an error ❌
// Check output
```

</details>

## Explanation of the bug

If we have this config:

```js
const legacyConfig = {
    rules: {
      'no-undef': 'error',
    },
    overrides: [{
        files: ['node.js'],
        env: {
            node: true
        },
    }]
}
```

With the legacy config, using `process.cwd()` shouldn't be allowed in a file like `no-node.js`, but allowed in `node.js`

<img width="989" alt="image" src="https://github.com/eslint/eslintrc/assets/22725671/c159da8d-9de0-491e-aba4-b5ebebb961f4">

And if we use `FlatCompat` to port it to the new structure, we should have the same result.

But when we do:

```js
const compat = new FlatCompat({
    baseDirectory: __dirname
});
const flatConfig = compat.config(legacyConfig);
```

We can see that the `files` and envs' config aren't merged together, instead we have 1 row for the `env`, and another one empty one for the overrides:

<img width="890" alt="image" src="https://github.com/eslint/eslintrc/assets/22725671/1a241180-b5ab-41ed-a536-e6168b720217">

And surely, when we run eslint with this config, no errors are reported (see the `""` x2):

<img width="1032" alt="image" src="https://github.com/eslint/eslintrc/assets/22725671/c58bcc6f-157a-40e6-ba17-3b0c43c9557a">

**Comment by Ayc0** [comment] 2023-08-02 22:06
I don't know if this one is a bug (but it seems related): using `compat.env()` on multiple envs generates multiple rows, but we may want to only have 1 item with all global merged properly

```js
compat.env({
    node: true,
    es2020: true
})
```

<img width="953" alt="image" src="https://github.com/eslint/eslintrc/assets/22725671/32331c52-5419-4b07-a0af-b43925248032">

**Comment by nzakas** [comment] 2023-08-03 19:23
Duplicate of https://github.com/eslint/eslintrc/issues/125. Continue conversation there.

**Comment by nzakas** [comment] 2023-08-03 19:29
I'm sorry, the reproduction case isn't very clear to me. What is it you're trying to show?

For what it's worth, we already know that configs with `overrides` work, there are a bunch of tests for it:
https://github.com/eslint/eslintrc/blob/6cfa0466c192f5c2aff1cdf9554836acd4fcce68/tests/lib/flat-compat.js#L391

If you'd like to add a test that shows what is failing, we can definitely take a look.

Regarding `compat.env()`, this is working as expected. It doesn't matter how many objects are created because they are merged at the end. Creating one object per environment makes the logic easier to follow.

**Comment by Ayc0** [comment] 2023-08-03 20:52
> I'm sorry, the reproduction case isn't very clear to me. What is it you're trying to show?

Using `compat.config` on a legacy config with `env` in `overrides` seem to generate the env outside of the overrides:

```js
const legacyConfig = compat.config({
    rules: {
      'no-undef': 'error',
    },
    overrides: [{
        files: ['node.js'],
        env: {
            node: true
        },
    }]
})
```

generates something like:

```js
[
  { rules: { no-undef: "error" }, // ✅ correct
  { languageOptions: { globals: { … }} }, // ⚠️ applied globally as there are no files
  { files() { … } }, // ⚠️ doesn't contain the globals
]
```

But my understanding of the flat config is that, as `languageOptions` is in its own element (without files), it'll be applied globally.
Which seems to the behavior shown in the REPL I linked: with the legacy config, the desired behavior was "on 1 file, eslint passes, and on the other one, it sends an error". But after using `compat.config`, flat eslint passes on both files.

Instead I'd imagine `compat.config` to generate this:
```js
[
  { rules: { no-undef: "error" }, // ✅ correct
  { languageOptions: { globals: { … }}, files() { … } }, // 👍 has both the files and the languageOptions
]
```

I can try to modify the test to showcase what I mean.

**Comment by Ayc0** [comment] 2023-08-03 20:55
> Regarding compat.env(), this is working as expected. It doesn't matter how many objects are created because they are merged at the end. Creating one object per environment makes the logic easier to follow

That's what I figured. I only mentioned this because this could make working with `overrides` a bit harder:  for instance such code:

```js
const legacyConfig = compat.config({
    overrides: [{
        files: ['node.js'],
        env: {
            node: true,
            es2020: true
        },
    }]
})
```

This may need to generate:

```js
[
  // The field `files()` is duplicated in both entries
  { languageOptions: { globals: { globals for node }}, files() { … } },
  { languageOptions: { globals: { globals for es2020 }}, files() { … } },
]
```

**Comment by Ayc0** [comment] 2023-08-03 21:32
I created the test here: https://github.com/eslint/eslintrc/compare/main...Ayc0:eslintrc:Ayc0/potential-bug-investigation?expand=1

If you want, I can open the PR

**Comment by nzakas** [comment] 2023-08-04 14:55
Thanks, I'll take a look.

As an FYI: the eslintrc-style configs are first translated into an intermediate form (the form that ESLint uses internally) and then into flat config format. The intermediate form doesn't exactly match either eslintrc or flat config formats, which is why there's not always a 1-to-1 matching in either direction.

**Closed** 2023-08-05 22:17 UTC
Labels: bug, accepted
